ibm_cloud_fail_over/__init__.py,sha256=WNrxDTz--FWGcrVobE9iwSYQndBvY9XULngT93fguXg,339
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=inwj1542kp0jPMkx-BEUCvG8pVzAxNrUBwlRzTfVV9c,30190
ibm_cloud_fail_over-1.0.17.dist-info/METADATA,sha256=oVRV1BywUW0uVHYMm4EeuEP4apD4kW35aOQi-SkCY4I,7105
ibm_cloud_fail_over-1.0.17.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.17.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.17.dist-info/RECORD,,
