ibm_cloud_fail_over/__init__.py,sha256=BsQuzbw97w9gjPOCuYt2ECNH7wgSRSeM2agIvybzmSU,532
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=gzqLPiKTttf2wQElma7Mxh4ZB-s4mR1FDunAvME7zRk,38736
ibm_cloud_fail_over-1.0.18.dist-info/METADATA,sha256=QGHSOBpC4pykBKcpI6-znb-mga2roUcVIL4pdGEcvyQ,10786
ibm_cloud_fail_over-1.0.18.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.18.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.18.dist-info/RECORD,,
